  email = "johan@persson.wien"
  AuthorName = "Johan Persson"
  greeting = "ğŸ‘‹ğŸ»"
  description = "I'm Johan. Husband, <a href='categories/kids'>father of sons</a>, <a href='/categories/cycling'>avid cyclist</a> and <a href='categories/food'>eater of plats</a>."
  github = "jpersson"
  twitter = "suraken"
  stats = true
