email = "please-no-spam@johanpersson.at"
gravatar = "f72cfa64db6af68f3dfd215404c636bf"
AuthorName = "Johan Persson"
greeting = "ğŸ‘‹ğŸ»"
description = "I'm Johan. Husband, <a href='categories/kids'>father of sons</a>, <a href='/categories/cycling'>avid cyclist</a> and <a href='categories/food'>eater of plants</a>."
github = "jpersson"
twitter = "suraken"
stats = true
